### PR TITLE
Fix #861 search select marker

### LINKED ISSUE #861: [Select All] Wrong display of the marker
# Actual behaviour

 When selecting all the elements resulting from the search or when selecting all the elements of a grouping, the marker changes to the following state :  image

image

<U> Bug1 </U>: When deselecting all the elements of the list or all the element of a grouping, the marker changes to the following state : image

image

<U> Bug2 </U>: When clicking on the <I>Deselect All</I> of a grouping, the marker changes to image but the elements of that specific grouping stay selected.

image

<U> Bug3 </U>: When clicking on the <I>Select All</I> of a grouping, the global marker stays to the following state : image

image

# Expected behaviour

<U> Bug1 </U>: When deselecting all the elements of the list or all the elements of a grouping, put the markers to state : image

<U> Bug2 </U>: When clicking on the <I>Deselect All</I> of a grouping, deselect all the elements of the grouping.

<U> Bug3 </U>: When clicking on the <I>Select All</I> of a grouping, put the global marker to the state : image

# Versions

Focus-core: 0.12.1
Focus-components: 0.8.4

### PR DESCRIPTION
**Pull request by Bernardstanislas**
### Description

See @mouffakb description in #861.

### Patch
Selection status is now correctly synced with the lines.
It is a button, directly clickable, not a dropdown anymore.
> Fixes #861

### CODE REVIEW

File: src/page/search/advanced-search/index.js [hunk 1]
```diff
@@ -297,7 +298,27 @@ const AdvancedSearch = {
     * Line selection handler
     */
     _selectItem() {
-        this.setState({selectionStatus: 'partial'});
+        const selectedItemsCount = this.getSelectedItems().length;
+        const visibleItemsCount = reduce(this.refs.resultList.refs, (visibleItemsCount, refComponent, refKey) => {
```
Comment (pierr) [inline src/page/search/advanced-search/index.js]: Add a comment to explain your strategy
