### PR TITLE
[Issue Fixed : [icon-dropdown] Secondary buttons label are not translated] Add translation #981

### LINKED ISSUE #980: [icon-dropdown] Secondary buttons label are not translated
# Current behaviour

In the dropdown of banner information buttons (dropdown appears for secondary actions), the label is not translated.

image

# Expected behaviour

The label should be translated.

image

## Versions

Focus-core: 0.12.4
Focus-components: 0.8.6

### PR DESCRIPTION
**Pull request by gideruette**
### Description

Translation is added on the label

### Patch [in case of a fix]

Translation is added on the label, and i18n mixin is added to the component

Fixes #980

### CODE REVIEW

File: src/components/icon-dropdown/index.js [hunk 1]
```diff
@@ -74,7 +75,7 @@ class Dropdown extends Component {
                     />
                 {visible &&
                     <div data-focus='dropdown-menu' data-position={openDirection} ref='dropdown'>
-                        {operationList.map(({label, action}, idx) => (<div key={idx} data-role='dropdown-item' onClick={this._operationActionWrapper(action)}>{label}</div>))}
+                        {operationList.map(({label, action}, idx) => (<div key={idx} data-role='dropdown-item' onClick={this._operationActionWrapper(action)}>{i18n.t(label)}</div>))}
```
Comment (Bernardstanislas) [inline src/components/icon-dropdown/index.js]: Almost there ! 
For `i18n`, you can't rely on the global variable `window.i18n`. It's considered as unstable.
But you did well : you used the `i18nMixin`. This will set a `i18n` method in your class, so instead of using `i18n.t()` you might want to use `this.i18n()`.
I let you change it and test, then I'll merge it.

Comment (Bernardstanislas) [inline src/components/icon-dropdown/index.js]: I didn't see at first, but here it's a real class, not a component. So instead of using `i18nMixin`, you might want to use the `TranslationBehaviour`, available [here](https://github.com/KleeGroup/focus-components/blob/develop/src%2Fbehaviours%2Ftranslation%2Findex.js). You can see an example [here](https://github.com/KleeGroup/focus-components/blob/develop/src%2Fcomponents%2Fpanel%2Findex.js#L19)

Comment (gideruette) [inline src/components/icon-dropdown/index.js]: I'm almost there, thanks

**Comment by Bernardstanislas** [comment]
@gideruette thank you very much !
