### PR TITLE
Header edit fix

### LINKED ISSUE #901: [Header] Gives up when edition mode changes
### Context
A long page (so that you can scroll) with Editable block (so that you can edit stuff).

### Actual behaviour
After scrolling, a simple click on the 'edit' button will set the data-deployed value to false. So the header juste fold as if we were on top of the page (but we're not) hiding itself from our view. 

Rq : after scrolling the header come back.
Rq2: The cancel button acts like the edit button. (to test : scroll during edition then cancel -> no more header!)

### Expected behaviour
The data-deployed shouldn't be changed on neither of the edit or cancel button.

### Versions
    "focus-components": "^0.8.4",
    "focus-core": "^0.12.3",
    "focus-file": "^0.1.2"

### PR DESCRIPTION
**Pull request by JabX**
Fix #901

### CODE REVIEW

File: src/components/layout/header-scrolling.js [hunk 1]
```diff
@@ -60,8 +60,13 @@ class HeaderScrolling extends Component {
     }
 
     /** @inheriteddoc */
-    componentWillReceiveProps({isDeployed}) {
-        this.setState({isDeployed}, this.handleScroll());
+    componentWillReceiveProps({mode, route, canDeploy, isDeployed}) {
+        this.setState({mode, route, canDeploy});
+        let routeChanged = route !== this.state.route;
```
Comment (pierr) [inline src/components/layout/header-scrolling.js]: `const` && `hasRouteChanged`

File: src/components/layout/header-scrolling.js [hunk 2]
```diff
@@ -60,8 +60,13 @@ class HeaderScrolling extends Component {
     }
 
     /** @inheriteddoc */
-    componentWillReceiveProps({isDeployed}) {
-        this.setState({isDeployed}, this.handleScroll());
+    componentWillReceiveProps({mode, route, canDeploy, isDeployed}) {
+        this.setState({mode, route, canDeploy});
+        const hasRouteChanged = route !== this.state.route;
+        const hasModeChanged = mode !== this.state.mode;
```
Comment (pierr) [inline src/components/layout/header-scrolling.js]: thanks!
