### PR TITLE
Fix layout bug

### LINKED ISSUE #1088: [Button] When the component is updated, it doesn't take the right "alt" property
# Current behaviour

On header buttons : when the component is updated, it doesn't take the right "alt" property. It takes one of the alt property value of the previous buttons.

Before update component : 

image

After update : 

image

# Expected behaviour

It might be a problem of translation on 
focus-components/src/common/button/action

On first load, it has the right behaviour.

image

## Versions

Focus-core: 0.13.0
Focus-components: 0.13.1

### PR DESCRIPTION
**Pull request by GuenoleK**
### Description

Button's alt attribute wasn't updating when a new button action was added

### Patch

It was caused aused by the .map index given in the key attribute. React did have a problem to update this.
Giving the label fixes the update.

> Fixes #1088

### CODE REVIEW

File: src/components/button/index.js [hunk 1]
```diff
@@ -113,7 +115,7 @@ class Button extends Component {
     _renderLabel = () => {
         const {label, shape} = this.props;
         if (label && 'fab' !== shape && 'icon' !== shape && 'mini-fab' !== shape ) {
-            return translate(label);
+            return label;
```
Comment (Bernardstanislas) [inline src/components/button/index.js]: No translation here ?

File: src/components/button/index.js [hunk 2]
```diff
@@ -3,6 +3,7 @@ import ReactDOM from 'react-dom';
 import builder from 'focus-core/component/builder';
 import {translate} from 'focus-core/translation';
```
Comment (Bernardstanislas) [inline src/components/button/index.js]: Not needed if you use the `TranslationBehaviour`
