### PR TITLE
[Scrollspy] Fix scrollspy responsive issues. fixes #712.

### LINKED ISSUE #712: [Responsive] Some problem with ScrollspyContent and cartridge Button
# Actual behaviour

When responsive size is mobile : scrollspy-content menu is still fixed and button are not well left aligned.

image

# Expected behaviour

Scrollpsy content menu should not be fixed.
Cartridge buttons should be align more on right side.

# Versions

Focus-components: 0.7.4

### PR DESCRIPTION
**Pull request by Tommass**
## Issue Description

Scrollspy-content and menu were are not well displayed on mobiles.

image

> Fixes #712 

## Patch

This patch gives a first answer to responsive problems.

> Be careful, these changes may have some impact on your project. But don't worry, it's quite easy to change it ! It is described below.

### widescreen size and tablet size

MDL grid are not used anymore, so the allocated size of scrollspy menu remains the same if the windows size change.

capture d ecran 2015-11-29 a 17 22 13

### mobile size

On mobile screens, scrollspy menu is not displayed anymore on the left but at the top of the content.

capture d ecran 2015-11-29 a 17 23 50

## To modify scrollspy menu width

The default size of the menu is 260px. It's maybe not what your project needs.
That's why you can override this default size by addeing the following CSS code in your `scrollspy-container.scss` SASS file:

```sass
$scrollspy-container-menu-size:220px;
$media-desktop-breakpoint: 840px !default;

@media (min-width: $media-desktop-breakpoint - 1) {
    [data-focus="scrollspy-container"] {
        [data-focus="sticky-menu"] {
            width: $scrollspy-container-menu-size;
        }
        [data-focus="scrollspy-container-content"] {
            margin-left: #{$scrollspy-container-menu-size + 10px};
        }
    }
}
```

### CODE REVIEW

**Comment by Tommass** [comment]
@pierr please have a look and make some test on démo app.
I will test modifications in CRf et trackit to prevent regressions.

File: src/components/scrollspy-container/index.js [hunk 1]
```diff
@@ -16,8 +16,8 @@ const defaultProps = {
     hasMenu: true, //Activate the presence of the sticky navigation component.
     hasBackToTop: true, //Activate the presence of BackToTop button
     offset: 80, //offset position when affix
-    gridMenuSize: 3, //default grid size of the menu
-    gridContentSize: 9, //default content size of the menu
+    //gridMenuSize: 3, //default grid size of the menu
```
Comment (pierr) [inline src/components/scrollspy-container/index.js]: Remove it

File: src/components/scrollspy-container/index.js [hunk 2]
```diff
@@ -26,8 +26,8 @@ const propTypes = {
     hasMenu: PropTypes.bool,
     hasBackToTop: PropTypes.bool,
     offset: PropTypes.number,
-    gridMenuSize: PropTypes.number,
-    gridContentSize: PropTypes.number,
+    //gridMenuSize: PropTypes.number,
```
Comment (pierr) [inline src/components/scrollspy-container/index.js]: same remark

**Comment by pierr** [comment]
@Tommass  Rebase your branch
